--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TitaniumLB6571/TitanCommandBlocker
build-by-default: true
branches:
- master
projects:
  TitanCommandBlocker:
    path: ""
    icon: "icon.png"
...
